# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-23 02:04
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [

        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name=b'Title')),
                ('details', models.TextField(blank=True, null=True, verbose_name=b'Details')),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(default=b'OpenBuild Team', max_length=100, verbose_name=b'author')),
            ],
        ),

        migrations.CreateModel(
            name='BlogAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=1000, upload_to=blog.models.attachment_path, verbose_name='File')),
                ('filename', models.CharField(max_length=1000, verbose_name='Filename')),
                ('mime_type', models.CharField(max_length=255, verbose_name='MIME Type')),
                ('size', models.IntegerField(help_text='Size of this file in bytes', verbose_name='Size')),
            ],
            options={
                'ordering': ['filename'],
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
            },
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500, verbose_name=b'Comment')),
                ('created_by', models.CharField(default=b'Anonymous', max_length=100, verbose_name=b'Sender')),
                ('sender_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name=b'Sender email ')),
                ('posted_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
              migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.CharField(max_length=500, verbose_name=b'Response')),
                ('created_by', models.CharField(default=b'Anonymous', max_length=100, verbose_name=b'Sender')),
                ('sender_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name=b'Sender email ')),
                ('posted_date', models.DateTimeField(blank=True, null=True)),
                ('blog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='blog.BlogPost')),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='blog.BlogComment')),
            ],
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='blog_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_comments', to='blog.BlogPost'),
        ),
        migrations.AddField(
            model_name='blogattachment',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.BlogPost', verbose_name=b'blog'),
        ),
    ]
