# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-04 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogattachment_blogcomment_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name=b'subscriber email ')),
            ],
        ),
    ]
