# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-03-09 09:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogsubscription'),
        ('blog', '0002_blogsubscription'),
    ]

    operations = [
    ]
