# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-16 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20160502_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='textblock',
            name='lesson_image',
            field=models.FileField(null=True, upload_to='lesson_images/'),
        ),
    ]
