# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-26 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_auto_20170418_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='textblock',
            name='lesson_name',
            field=models.CharField(default='Untited Lesson', max_length=50),
        ),
    ]
