# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-28 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_textblock_lesson_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textblock',
            name='lesson_name',
            field=models.CharField(default='Untitled Lesson', max_length=50),
        ),
    ]
