# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-02 03:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StepsConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.CharField(max_length=50)),
                ('placement', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=50)),
                ('path', models.CharField(max_length=50)),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='stepsconfig',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptours.Tour'),
        ),
    ]
