# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-02 06:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apptours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepsconfig',
            name='tour',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apptours.Tour'),
        ),
        migrations.AlterField(
            model_name='stepsconfig',
            name='content',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='stepsconfig',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
