# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-02 06:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apptours', '0002_auto_20170602_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stepsconfig',
            name='tour',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='apptours.Tour'),
        ),
    ]
