# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-06 05:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apptours', '0004_auto_20170602_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptours.Tour'),
        ),
    ]
