# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-06 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptours', '0005_auto_20170606_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='tour_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
