# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-06 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptours', '0008_auto_20170628_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='tour_groups',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='tour',
            name='tour_image',
            field=models.TextField(default=''),
        ),
    ]
