# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-07 00:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('apptours', '0009_auto_20170706_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='tour_create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 7, 0, 25, 15, 666095, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tour',
            name='tour_groups',
            field=models.CharField(default='users professors admin', max_length=25),
        ),
    ]
