# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-30 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptours', '0010_auto_20170707_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='tour_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='tour',
            name='tour_update_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tour_groups',
            field=models.CharField(default='users professors admin ', max_length=25),
        ),
    ]
