# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-30 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptours', '0011_auto_20170730_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='tour_description',
            field=models.TextField(default='', null=True),
        ),
    ]
