# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-01 06:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apptours', '0012_auto_20170730_0102'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='tour',
            name='tour_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tourusers',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptours.Tour'),
        ),
        migrations.AddField(
            model_name='tourusers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
